[package]
name = "tui_template"
version = "0.1.0"
authors = ["Konstantin Gorodinskii <mail@konstantin.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.15"
termion = "1.0.0"
